version: '3.8'

services:
  web-service:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "host.docker.internal:29092"
    depends_on:
      - kafka