services:
  app:
    build:
      context: .
    container_name: my-python-app
    ports:
      - "4898:4898"
    environment:
      KAFKA_BROKER: kafka:29092
    volumes:
      - .:/app
    working_dir: /app
    command: python app.py
    networks:
      - sberflow-net

networks:
  sberflow-net:
    external: true